version: '3.8'

services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    command: >
      sh -c "aerich upgrade && uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: